REM INSERTING into XX_APX_EBS_APPLICATIONS
SET DEFINE OFF;
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('1','XBOL','XX Customizaciones');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('2','FND','Application Object Library');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('3','SYSADMIN','System Administration');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('4','AU','Application Utilities');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('5','AD','Applications DBA');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('6','SHT','Applications Shared Technology');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('7','SQLGL','General Ledger');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('8','OFA','Assets');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('9','ALR','Alert');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('10','RG','Application Report Generator');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('11','CS','Service');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('12','CCT','Telephony Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('13','ECX','XML Gateway');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('14','EC','e-Commerce Gateway');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('15','ICX','Oracle iProcurement');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('16','XTR','Treasury');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('17','AZ','Application Implementation');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('18','BIS','Applications BIS');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('19','SQLAP','Payables');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('20','PO','Purchasing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('21','CHV','Supplier Scheduling');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('22','AR','Receivables');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('23','PN','Property Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('24','QA','Quality');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('25','CE','Cash Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('26','FRM','Report Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('27','EAA','SEM Exchange (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('28','BSC','Tablero de Comando Integral');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('29','ABM','Activity Based Management (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('30','EVM','Value Based Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('31','FEM','Enterprise Performance Foundation');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('32','PA','Projects');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('33','AS','Sales Foundation');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('34','CN','Incentive Compensation');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('35','POM','Exchange');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('36','OE','Order Entry');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('37','WMS','Warehouse Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('38','WPS','Manufacturing Scheduling');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('39','INV','Inventory');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('40','MWA','Mobile Applications');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('41','WSM','Shop Floor Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('42','FII','Financial Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('43','OPI','Operations Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('44','POA','Purchasing Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('45','HRI','Human Resources Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('46','ISC','Supply Chain Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('47','AN','Sales Analysis');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('48','OKC','Contracts Core');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('49','CSC','Customer Care');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('50','CSD','Depot Repair');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('51','CSF','Field Service');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('52','CSS','Support (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('53','OKS','Service Contracts');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('54','ME','Controlled Availability Product (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('55','BIM','Marketing Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('56','BIC','Customer Intelligence (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('57','IES','Scripting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('58','AMV','Marketing Encyclopedia System');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('59','AST','TeleSales');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('60','ASF','Sales Online');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('61','CSP','Spares Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('62','OKX','Contracts Integration');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('63','ODQ','Data Query');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('64','AMS','Marketing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('65','XNM','Marketing for Communications (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('66','XNC','Sales for Communications (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('67','XNS','Service for Communications (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('68','XNP','Number Portability');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('69','XDP','Provisioning');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('70','FPT','Banking Center (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('71','IEO','Interaction Center Technology');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('72','GMA','Process Manufacturing Systems');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('73','GMI','Process Manufacturing Inventory');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('74','GMD','Process Manufacturing Product Development');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('75','GME','Process Manufacturing Process Execution');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('76','GMP','Process Manufacturing Process Planning');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('77','GMF','Process Manufacturing Financials');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('78','GML','Process Manufacturing Logistics');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('79','GR','Process Manufacturing Regulatory Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('80','PMI','Process Manufacturing Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('81','AX','Global Accounting Engine');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('82','DPP','Oracle Price Protection');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('83','MTH','Oracle Manufacturing Operations Center');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('84','QPR','Oracle Deal Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('85','DDR','Demand Signal Repository');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('86','INL','Oracle Landed Cost Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('87','AK','Common Modules-AK');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('88','XLA','Subledger Accounting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('89','ONT','Order Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('90','QP','Advanced Pricing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('91','RLM','Release Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('92','VEA','Automotive');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('93','WSH','Shipping Execution');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('94','IBA','iMarketing (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('95','IBE','iStore');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('96','IBU','iSupport');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('97','IBY','Pagos');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('98','IBP','Bill Presentment & Payment');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('99','BIL','Sales Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('100','BIX','Interaction Center Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('101','IEM','Email Center');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('102','OZP','Trade Planning (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('103','OZF','Trade Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('104','OZS','iClaims (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('105','ASG','CRM Gateway para Dispositivos MÃ³viles');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('106','JTF','CRM Foundation');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('107','IEX','Collections');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('108','IEU','Universal Work Queue');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('109','ASO','Order Capture');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('110','CSR','Scheduler');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('111','IEB','Interaction Blending');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('112','MFG','Manufacturing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('113','BOM','Bills of Material');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('114','ENG','Engineering');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('115','MRP','Master Scheduling/MRP');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('116','CRP','Capacity');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('117','WIP','Work in Process');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('118','CST','Cost Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('119','CZ','Configurator');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('120','RLA','Release Management Integration Kit (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('121','VEH','Automotive Integration Kit (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('122','PJM','Project Manufacturing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('123','FLM','Flow Manufacturing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('124','MSD','Demand Planning');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('125','MSO','Constraint Based Optimization');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('126','MSC','Advanced Supply Chain Planning');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('127','RHX','Advanced Planning Foundation (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('128','OKE','Project Contracts');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('129','PER','Human Resources');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('130','PAY','Payroll');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('131','FF','FastFormula');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('132','DT','DateTrack');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('133','SSP','SSP');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('134','BEN','Advanced Benefits');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('135','HXT','Time and Labor');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('136','HXC','Motor de Time and Labor');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('137','OTA','Learning Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('138','JA','Asia/Pacific Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('139','JE','European Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('140','JG','Regional Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('141','JL','Latin America Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('142','GHR','US Federal Human Resources');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('143','PQH','Public Sector HR');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('144','PQP','Public Sector Payroll');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('145','PSB','Public Sector Budgeting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('146','GMS','Grants Accounting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('147','PSP','Labor Distribution');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('148','IGW','Grants Proposal');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('149','IGS','Student System');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('150','IGF','Financial Aid');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('151','IGC','Contract Commitment');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('152','PSA','Public Sector Financials');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('153','IPA','Capital Resource Logistics - Projects');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('154','CUI','Network Logistics - Inventory');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('155','CUP','Network Logistics - Purchasing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('156','CUF','Capital Resource Logistics - Financials');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('157','CUS','Network Logistics');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('158','CUN','Network Logistics - NATS (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('159','CUA','Capital Resource Logistics - Assets');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('160','FV','Federal Financials');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('161','CUE','Billing Connect (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('162','EAM','Enterprise Asset Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('163','FTE','Transportation Execution');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('164','IGI','Public Sector Financials International');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('165','ITG','Internet Procurement Enterprise Connector');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('166','MSR','Inventory Optimization');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('167','PV','Partner Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('168','ASL','Sales Offline');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('169','POS','iSupplier Portal');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('170','AHM','Hosting Manager (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('171','ASP','Oracle Sales for Handhelds');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('172','BIV','Service Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('173','CSI','Install Base');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('174','CSL','Field Service/Laptop');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('175','CUG','Citizen Interaction Center');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('176','IMT','iMeeting (obsolete)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('177','OKI','Contracts Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('178','IEC','Advanced Outbound Telephony');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('179','CSE','Asset Tracking');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('180','OKO','Contracts for Sales (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('181','JTS','CRM Self Service Administration');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('182','JTM','Mobile Application Foundation');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('183','AHL','Complex Maintenance Repair and Overhaul');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('184','OKB','Contracts for Subscriptions (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('185','IMC','Customers Online');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('186','XNI','Install Base Intelligence (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('187','OKR','Contracts for Rights (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('188','IPD','Product Development (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('189','ENI','Product Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('190','BNE','Web Applications Desktop Integrator');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('191','QRM','Risk Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('192','PON','Sourcing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('193','OKL','Lease and Finance Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('194','IBC','Content Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('195','AMF','Fulfillment Services (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('196','QOT','Quoting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('197','CSM','Field Service/Palm');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('198','DOM','Document Managment and Collaboration');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('199','EGO','Advanced Product Catalog');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('200','DDD','CADView-3D');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('201','PJI','Project Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('202','XNB','Oracle Telecommunications Billing Integrator');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('203','ZFA','Financial Analyzer');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('204','ZSA','Sales Analyzer');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('205','CLN','Supply Chain Trading Connector for RosettaNet');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('206','EDR','E-Records');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('207','PRP','Proposals');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('208','IZU','Oracle E-Business Suite Diagnostics');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('209','JMF','Supply Chain Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('210','ITA','Information Technology Audit');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('211','IRC','iRecruitment');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('212','GMO','Manufacturing Execution System for Process Manufacturing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('213','IPM','AdministraciÃ³n de Proceso de Oracle Imaging');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('214','IBW','Oracle Web Analytics');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('215','AMW','Internal Controls Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('216','XLE','Legal Entity Configurator');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('217','ASN','Sales');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('218','MST','Transportation Planning');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('219','FUN','Financials Common Modules');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('220','GCS','Financial Consolidation Hub');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('221','XDO','XML Publisher');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('222','ZX','E-Business Tax');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('223','LNS','Loans');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('224','IA','iAssets');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('225','FPA','Project Portfolio Analysis');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('226','ZPB','Enterprise Planning and Budgeting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('227','WMA','Manufacturing Mobile Applications');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('228','ISX','iSettlement');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('229','MIV','Media Interactive');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('230','OAM','Oracle Applications Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('231','BIE','eCommerce Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('232','BIN','Communications Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('233','CUC','Revenue Accounting');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('234','CUR','Mass Market Receivables for Comms');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('235','IBT','iAuction');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('236','XNA','Service Assurance for Communications');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('237','XNT','TeleBusiness for Telecom/Utilities');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('238','MQA','Mobile Quality Applications');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('239','CTB','Clinical Transaction Base');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('240','IET','Call Center Connectors');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('241','IEV','IVR Integrator');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('242','IEP','Predictive');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('243','HCP','Healthcare Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('244','HCA','Healthcare');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('245','PBR','Budgeting and Planning');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('246','IAM','Digital Asset Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('247','OKT','Royalty Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('248','GNI','Genealogy Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('249','CPGC','CPG - CDOA');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('250','HCC','iHCConnect');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('251','HCN','iHCIntegrate');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('252','AME','Approvals Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('253','OKP','Contracts for Procurement (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('254','HCT','Healthcare Terminology Server');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('255','MIA','Mobile Applications for Inventory Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('256','GMW','Process Manufacturing Portal');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('257','BIY','Systems Intelligence');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('258','PFT','Oracle Profitability Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('259','RMG','Risk Manager');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('260','FTP','Transfer Pricing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('261','DNA','Development');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('262','BLC','Utility Billing');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('263','PTX','Patch Tracking System');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('264','EMS','Environment Management System');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('265','RCM','Regulatory Capital Manager (obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('266','OUC','University Curriculum');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('267','TEST','prueba');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('268','PSR','Public Sector Receivables');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('269','CDR','Oracle Clinical Data Repository');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('270','DUMMY_GMO','Process Operations (Obsoleto)');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('271','CLJ','Japan Consulting Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('272','OKC_REP_TXT_INDEX_SYNC','Actualizar/sincronizar Ãndice de Texto de Repositorio de Contratos');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('273','OKC_REP_TXT_INDEX_OPTIMIZE','Optimizar Ãndice de Texto de Repositorio de Contratos');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('274','DEM01','Equipo 01 - Demo de Order Entry');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('275','RRC','Retail Core');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('276','CLL','LAD Consulting Localizations');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('277','CSN','Centro de Llamadas');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('278','RRS','Site Management');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('279','CLA','APAC - Localizaciones de ConsultorÃ­a');
Insert into XX_APX_EBS_APPLICATIONS (APP_APX_ID,APP_CODE,APP_DESCRIPTION) values ('280','CLE','EMEA Consulting Localizations');
Commit;