 CREATE TABLE "XX_APX_FND_PARAMS" 
   (	"ID_PARAM" NUMBER NOT NULL ENABLE, 
	"SEQUENCE" NUMBER, 
	"LINE_TYPE_CODE" VARCHAR2(50), 
	"EXECUTION_TYPE" VARCHAR2(30), 
	"EXECUTABLE" VARCHAR2(150), 
	"PARAMETER1" VARCHAR2(150), 
	"PARAMETER2" VARCHAR2(150), 
	"PARAMETER3" VARCHAR2(150), 
	"PARAMETER4" VARCHAR2(150), 
	"PARAMETER5" VARCHAR2(150), 
	"PARAMETER6" VARCHAR2(150), 
	"PARAMETER7" VARCHAR2(150), 
	"PARAMETER8" VARCHAR2(150), 
	"PARAMETER9" VARCHAR2(150), 
	"PARAMETER10" VARCHAR2(150), 
	"ENABLED" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	 CONSTRAINT "XX_APX_FND_PARAMS_PK" PRIMARY KEY ("ID_PARAM")
  USING INDEX  ENABLE
   ) ;
   /

   SHOW err

EXIT