CREATE TABLE "XX_APX_SRCH_OBJ_GTT" 
   (	"OBJ_CODE" VARCHAR2(50 CHAR), 
	"OBJ_DESCRIPTION" VARCHAR2(500 CHAR), 
	"APP_ID" NUMBER, 
	"APP_NAME" VARCHAR2(240 CHAR), 
	"APP_SHORT_NAME" VARCHAR2(50 CHAR), 
	"OBJ_TYPE" VARCHAR2(2000 CHAR), 
	"OBJ_NAME" VARCHAR2(2400 CHAR), 
	"OBJ_DESC" VARCHAR2(4000 CHAR), 
	"SESSION_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"ADDITIONAL_1" VARCHAR2(4000), 
	"ADDITIONAL_2" VARCHAR2(4000), 
	"ADDITIONAL_3" VARCHAR2(4000), 
	"ADDITIONAL_4" VARCHAR2(4000), 
	"ID_SRCH" NUMBER NOT NULL ENABLE
   ) ;

--  CREATE OR REPLACE EDITIONABLE TRIGGER "XX_APX_SRCH_OBJ_GTT_TRG" 
--before
--insert or update on "XX_APX_SRCH_OBJ_GTT"
--for each row
--begin
    --if :new.id_srch is null then
        --select XX_APX_SRCH_SEQ.nextval into :new.id_srch from sys.dual;
    --end if;
--end;
--/
--ALTER TRIGGER "XX_APX_SRCH_OBJ_GTT_TRG" ENABLE;
/
SHOW err

EXIT