SET ECHO ON
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Drop ORDS schemas to allow clean reinstall
DROP USER ORDS_PUBLIC_USER CASCADE;
DROP USER ORDS_METADATA CASCADE;

-- APEX_PUBLIC_ROUTER is also created by ORDS proxy setup; leave APEX_PUBLIC_USER alone (it's owned by APEX)
BEGIN
  EXECUTE IMMEDIATE 'DROP USER ORDS_PLSQL_GATEWAY CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

EXIT;
